/** @format */

import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './redux/providers';
import Head from 'next/head';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by Next Js App',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meat name={metadata.name} content={metadata.description} />
      </Head>
      <body className={inter.className} suppressHydrationWarning={true}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
